### ISSUE TITLE
Ada crasha ao tentar acessar uma rota inexistente

### ISSUE THREAD

**Issue by pedro823** [IMEsec-USP/issues#13]
**Boa primeira issue!**

Alguém tava tentando mapear a ada:

```
[2020-05-18 21:17:59 +0000] [11] [ERROR] Error handling request /wp-login.php
Traceback (most recent call last):
File "/root/.local/share/virtualenvs/ada-AC2CTCIc/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 134, in handle
self.handle_request(listener, req, client, addr)
File "/root/.local/share/virtualenvs/ada-AC2CTCIc/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
File "/root/.local/share/virtualenvs/ada-AC2CTCIc/lib/python3.8/site-packages/falcon/api.py", line 286, in __call__
    process_response(req, resp, resource, req_succeeded)
File "/ada/middleware/logger.py", line 7, in process_response
    if resource.ignore_middleware_log:
AttributeError: 'NoneType' object has no attribute 'ignore_middleware_log'
```

A ada crasha um worker por causa disso. A solução é um null check.

**Comment by pedro823** [comment]
This was fixed by [#14](https://github.com/IMEsec-USP/ada/pull/14).
